#!/bin/bash

## Get time
get_time() {
	time=`amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1`
	if [[ -z "$time" ]]; then
		echo "0"
	else
		echo "$time"
	fi	
}


## Execute accordingly
if [[ "$1" == "--time" ]]; then
	get_time
fi